### PR TITLE
Fixed/Added few things

### LINKED ISSUE #13: Scoping

### LINKED ISSUE #19: Make it unable to modify constants

### PR DESCRIPTION
**Pull request by Majd223**
- can't edit constant now
- created stack for future use with scoping
- changed from variableDeclerationList to VariableStatemenet
- You can define more than one variable now at the same time

### CODE REVIEW

File: src/stack.ts [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+    push(item: T): void;
+    pop(): T | undefined;
+    peek(): T | undefined;
+    size(): number;
+}
+
+export class Stack<T> implements IStack<T> {
+    private storage: T[] = [];
+
+    constructor(mainDetectedVariableStatements: VariableStatementAnalysis[]) {}
```
Comment (wandyezj) [inline src/stack.ts]: I like the generic stack! :) 

What is this parameter in the constructor for?

File: test/analyzeCode.test.ts [hunk 2]
```diff
@@ -78,8 +82,8 @@ test("Edit variable", () => {
 });
 
 test("PrefixUnaryExpression and PrefixUnaryExpression", () => {
-    const code = `const f = -5;
-                const w = +6;
+    const code = `var f = -5;
```
Comment (wandyezj) [inline test/analyzeCode.test.ts]: Generally, in JavaScript it's preferable to use `let` instead of `var`. `var` has scoping rules you wouldn't expect.

[MDN var](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var)

[MDN let](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let)

File: src/stack.ts (hunk 1 above)
Comment (Majd223) [reply src/stack.ts]: Since it will be used for scoping, variables defined in the general scope can be used in a specific scope (like an if statement)
So i want to pass the variables of the previous scope to the new scope and maybe create a new array that collects the variables of the new scope or something like that
unless you have a different idea on how to use the stack!

**Comment by Majd223** [comment]
We can merge the scoping draft to main since i did some other fixes in other places. 
the scoping branch have the updated features compared to main.

File: test/analyzeCode.test.ts (hunk 2 above)
Comment (Majd223) [reply test/analyzeCode.test.ts]: Good resources. Resolved the issue!

**Review by wandyezj — APPROVED** [review]

**Review by wandyezj — APPROVED** [review]
